- name: Create (or delete) a tenant in ACI
  hosts:  localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Create a tenant
      aci_tenant:
        host: 10.64.4.13
        username: admin
        password: bagofd0nuts!
        validate_certs: false
        tenant: STT-On-The-Fly
        state: present
      delegate_to: localhost

    - name: Create a bridge domain
      aci_bd:
        host: 10.64.4.13
        username: admin
        password: bagofd0nuts!
        validate_certs: false
        tenant: STT-On-The-Fly
        bd: database
        state: present
      delegate_to: localhost

    - name: Create a subnet
      aci_bd_subnet:
        host: 10.64.4.13
        username: admin
        password: bagofd0nuts!
        validate_certs: false
        tenant: STT-On-The-Fly
        bd: database
        gateway: 10.1.1.1
        mask: 24
        state: present
      delegate_to: localhost

    - name: Create a subnet with options
      aci_bd_subnet:
        host: 10.64.4.13
        username: admin
        password: bagofd0nuts!
        validate_certs: false
        tenant: STT-On-The-Fly
        bd: database
        subnet_name: sql
        gateway: 10.1.2.1
        mask: 23
        description: SQL Servers
        scope: public
        route_profile_l3_out: corp
        route_profile: corp_route_profile
        state: present
      delegate_to: localhost

    - name: Update a subnets scope to private and shared
      aci_bd_subnet:
        host: 10.64.4.13
        username: admin
        password: bagofd0nuts!
        validate_certs: false
        tenant: STT-On-The-Fly
        bd: database
        gateway: 10.1.1.1
        mask: 24
        scope: [private, shared]
        state: present
      delegate_to: localhost
