- name: Create (or delete) a tenant in ACI
  hosts:  localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Add a new AP
      aci_ap:
        hostname: 10.64.4.13
        username: admin
        password: bagofd0nuts!
        validate_certs: false
        tenant: STT-On-The-Fly
        ap: myappprofile
        description: default ap
        state: present
      delegate_to: localhost