---
- hosts: tag_ansible_role_netbox
  become: yes
  
  pre_tasks:
    - name: Enable Subscription Manager Repos
      rhsm_repository:
        name: "{{ item }}"
      loop:
        - rhel-*-optional-rpms
        - rhel-*-extras-rpms
    - name: Enable/Install EPEL Repo
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - name: Enable/Install PostgreSQL Repo
      yum:
        name: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-redhat10-10-2.noarch.rpm
      
  roles:
    - geerlingguy.postgresql
    - lae.netbox
    - nginxinc.nginx

  post_tasks:
    - name: Allow NGINX to network connect
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
    - name: Remove default server config from NGINX
      file:
        state: absent
        path: /etc/nginx/conf.d/default.conf
      notify: "(Handler: All OSs) Reload NGINX"
    - name: Ensure SSL directory for NGINX exists
      file:
        state: directory
        path: /etc/nginx/ssl
        mode: 0640
    - name: "Place SSL cert for {{ ansible_fqdn }} in NGINX directory"
      copy:
        content: "{{ kpsc_ssl_cert }}"
        dest: "/etc/nginx/ssl/{{ nginx_server_kpsc }}_cert.pem"
      notify: "(Handler: All OSs) Reload NGINX"
    - name: "Place SSL key for {{ ansible_fqdn }} in NGINX directory"
      copy:
        content: "{{ kpsc_ssl_key }}"
        dest: "/etc/nginx/ssl/{{ nginx_server_kpsc }}_key.pem"
      notify: "(Handler: All OSs) Reload NGINX"
    - name: Place SSL cert for netbox.kovarus.com in NGINX directory
      copy:
        content: "{{ kovarus_ssl_cert }}"
        dest: "/etc/nginx/ssl/netbox.kovarus.com_cert.pem"
      notify: "(Handler: All OSs) Reload NGINX"
    - name: Place SSL key for netbox.kovarus.com in NGINX directory
      copy:
        content: "{{ kovarus_ssl_key }}"
        dest: /etc/nginx/ssl/netbox.kovarus.com_key.pem
      notify: "(Handler: All OSs) Reload NGINX"
    - name: Create proxy.conf for NGINX
      template:
        src: roles_files/netbox_nginx/proxy.conf.j2
        dest: /etc/nginx/conf.d/proxy.conf
      notify: "(Handler: All OSs) Reload NGINX"
    - name: Create redirect.conf for NGINX
      copy:
        src: roles_files/netbox_nginx/redirect.conf
        dest: /etc/nginx/conf.d/redirect.conf
      notify: "(Handler: All OSs) Reload NGINX"
