---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: configuration
    inherits: 
    description: 
  fields:
  - print_evm_object:
      value: 'false'
  - print_evm_parent:
      value: 'false'
  - print_nil_values:
      value: 'true'
  - walk_association_policy:
      value: whitelist
  - walk_association_whitelist:
      value: "{'MiqAeServiceServiceTemplateProvisionTask':['source','destination','miq_request','miq_request_task','miq_request_tasks','service_resource'],
        'MiqAeServiceServiceTemplateProvisionRequest':['miq_request','miq_request_tasks','requester','resource','source'],
        'MiqAeServiceServiceTemplate':['service_resources'], 'MiqAeServiceServiceResource':['resource','service_template'],
        'MiqAeServiceMiqProvisionRequest':['miq_request','miq_request_tasks','miq_provisions','requester','resource','source','vm_template'],
        'MiqAeServiceMiqProvisionRequestTemplate':['miq_request','miq_request_tasks'],
        'MiqAeServiceManageIQ_Providers_Vmware_InfraManager_Provision':['source','destination','miq_provision_request','miq_request','miq_request_task','vm','vm_template'],
        'MiqAeServiceManageIQ_Providers_Redhat_InfraManager_Provision':['ALL'], 'MiqAeServiceManageIQ_Providers_Amazon_CloudManager_Vm':['availability_zone','cloud_network','cloud_subnet','cloud_subnets'],
        'MiqAeServiceManageIQ_Providers_Vmware_InfraManager_Vm':['ems_cluster','ems_folder','resource_pool','ext_management_system','storage','service','hardware','operating_system'],
        'MiqAeServiceManageIQ_Providers_Redhat_InfraManager_Vm':['ems_cluster','resource_pool','ext_management_system','storage','service','hardware'],
        'MiqAeServiceManageIQ_Providers_Azure_CloudManager_Vm':['availability_zone','cloud_networks','cloud_subnets'],
        'MiqAeServiceManageIQ_Providers_Google_CloudManager_Vm':['flavor','floating_ip'],
        'MiqAeServiceManageIQ_Providers_Openstack_CloudManager_Vm':['miq_provision','network_ports','network_routers','operating_system'],
        'MiqAeServiceHardware':['nics','guest_devices','ports','vm'], 'MiqAeServiceUser':['current_group','current_tenant'],
        'MiqAeServiceGuestDevice':['hardware','lan','network'], 'MiqAeServiceManageIQ_Providers_Redhat_InfraManager_Template':['operating_system'],
        'MiqAeServiceManageIQ_Providers_AnsibleTower_ConfigurationManager_ConfigurationScript':['ALL'],
        'MiqAeServiceManageIQ_Providers_AnsibleTower_ConfigurationManager_Job':['ALL']}"
